# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lookup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('referrer', models.URLField(null=True)),
                ('when', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'lookups',
            },
        ),
        migrations.CreateModel(
            name='slug',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField(default='http://skinny.dev')),
                ('slug', models.SlugField()),
            ],
            options={
                'db_table': 'slugs',
            },
        ),
        migrations.AddField(
            model_name='lookup',
            name='slug_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skinnyapp.slug'),
        ),
    ]
