# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skinnyapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slug',
            old_name='slug',
            new_name='slugname',
        ),
    ]
