# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skinnyapp', '0002_auto_20161113_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slug',
            old_name='slugname',
            new_name='slug',
        ),
        migrations.AlterField(
            model_name='lookup',
            name='slug_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skinnyapp.Slug'),
        ),
    ]
